module.exports = {
  parser: "@babel/eslint-parser",
  extends: ["eslint:recommended", "plugin:react/recommended", "prettier"],
  plugins: [
    "prettier",
    "sort-destructure-keys",
    "sort-keys-fix",
    "simple-import-sort",
  ],
  rules: {
    "no-case-declarations": "off",
    "no-console": "off",
    "prettier/prettier": "error",
    "react/jsx-sort-props": "error",
    "react/prop-types": "off",
    "react/react-in-jsx-scope": "off",
    "sort-destructure-keys/sort-destructure-keys": "error",
    "sort-keys-fix/sort-keys-fix": "error",
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
  },
  globals: {
    __DEV__: true,
    clearInterval: true,
    clearTimeout: true,
    console: true,
    document: true,
    fetch: true,
    localStorage: true,
    module: true,
    navigator: true,
    process: true,
    require: true,
    setInterval: true,
    setTimeout: true,
    URL: true,
    window: true,
  },
  env: {
    es6: true,
  },
};
